# Generated by Django 4.0.10 on 2023-06-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.CheckConstraint(check=models.Q(('post_id__isnull', False), ('comment_id__isnull', False), _connector='OR'), name='post_or_comment'),
        ),
    ]
